[package]
name = "rust-web-serve"
version = "1.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12.4", features = ["json", "cookies","blocking"] }
serde_json = "1.0"
chrono = "0.4"
http = "0.2"
regex = "1"
percent-encoding = "2.1.0"
url = "2"